### ISSUE TITLE
Fix for Samsung Galaxy A72

### ISSUE THREAD

**Issue by ModiFlasher** [MindTheGapps/13.0.0-arm64#2]
When i install this gapps on LineageOS its missing setup wizard and velvet

**Comment by javelinanddart** [comment]
This means your device doesn't have enough space or memory (or both) to accommodate Google SuW and Velvet.

**Comment by ModiFlasher** [comment]
![Screenshot_20231018-072440_DiskInfo](https://github.com/MindTheGapps/13.0.0-arm64/assets/13981274/1766d432-b857-403b-9640-a9637abc6855)
Do you mean talking about system partition or what ?

**Comment by javelinanddart** [comment]
It really depends on your device. If your device has dynamic partitions, typically this is indicative of not having enough _reserved_ space in either the product or system_ext partitions (on recent Android versions). You haven't given me much to work with here for details, but the issue is not a MindTheGapps issue.
